- name: Ensure Zuul Cache staging directory
  file:
    state: directory
    path: "{{ zuul_cache_dir }}"
    mode: 0755

- name: Archive artifact to local cache
  archive:
    dest: "{{ zuul_cache_dir }}/{{ zuul_cache_name }}"
    path: "{{ zuul_cache_src }}"
    format: "{{ zuul_cache_archive_format | default(omit) }}"
    force_archive: true
    mode: 0755
