- name: List artifacts to update
  find:
    paths: "{{ zuul_cache_dir }}/"
    recurse: no
  register: _zuul_cache_s3_artifacts

- name: Prepare upload urls for artifacts
  delegate_to: localhost
  zuul_cache_s3_urls:
    zuul: "{{ zuul }}"
    bucket: "{{ zuul_cache.bucket }}"
    artifacts: "{{ _zuul_cache_s3_artifacts.files | map(attribute='path') | list }}"
    method: put
    expiry: "{{ zuul_cache.url_expiry | default(omit) }}"
    aws_access_key: "{{ zuul_cache.access_key | default(omit) }}"
    aws_secret_key: "{{ zuul_cache.secret_key | default(omit) }}"
    s3_url: "{{ zuul_cache.url | default(omit) }}"
  register: _zuul_cache_s3_artifact_urls
  no_log: true

- name: Upload artifacts
  no_log: true
  include_tasks: batch-upload.yaml
  loop: "{{ _zuul_cache_s3_artifact_urls.urls | dict2items | batch(10) | list }}"
  loop_control:
    loop_var: zj_batched_artifacts
